version: '3.5'

networks:
  app-tier:
    driver: bridge

services:
  nest:
    # image: node:18
    build:
      context: ../
      dockerfile: .ci/Dockerfile
    container_name: lucy-app
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - app-tier
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lucy-db
    restart: always
    environment:
      MYSQL_DATABASE: 'lucy'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - app-tier
